### ISSUE TITLE
Define stable format for the extracted article data and include title for all articles

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/misinformation-crawler#9]
## Problem
When generalising the initial 21 custom crawlers to a smaller set of configurable generic crawlers (see issue #2), the specific fields for title, authors and publication date were removed.

## Implementation notes
We now export the following `Article` data structure, serialised inserted directly into the database.

```python
class Article(scrapy.Item):
    crawl_id = scrapy.Field() # UUID (version 4) as string
    crawl_date = scrapy.Field() # ISO 8601 date-time format with timezone info
    site_name = scrapy.Field() # Site domain (no protocol or path elements)
    article_url = scrapy.Field() # Full URL of article
    title = scrapy.Field() # Title text
    author = scrapy.Field() # Text containing author(s) names
    publication_date = scrapy.Field() # ISO 8601 date-time format **without** timezone info
    plain_content = scrapy.Field() # JSON array of non-empty paragraphs (with <br>'s converted to paragraph breaks) with HTML tags stripped
    structured_content = scrapy.Field() # JSON array of paragraphs (explicit only) with HTML retained
    metadata = scrapy.Field() # JSON key-value field holding arbitrary additional metadata fields
```

The site configuration yaml now permits the specification of selectors for arbitrary metadata fields, as well as whether to extract all matching elements or only the first element. `match-rule: 'all'`, will always result in an array for that metadata field in the export, even if only one element is found. Note that only xpath selectors are supported at this time.

```yaml
addictinginfo.com:
  site_name: 'addictinginfo.com'
  start_url: 'http://addictinginfo.com/category/news/'
  follow_url_path: 'page/'
  article_url_xpath: '//h2[@class="entry-title"]/a'
  metadata_source: 'microdata'
  article_search: 'paged'
  article_element: 'div'
  article_class: 'entry-content'
  metadata:
    title:
      select-method: 'xpath'
      select-expression: '//h1[@class="entry-title"]/a/text()'
      match-rule: 'first'
    author:
      select-method: 'xpath'
      select-expression: '//div[@class="post-meta"]/span/a/text()'
      match-rule: 'first'
    publication_date:
      select-method: 'xpath'
      select-expression: '//div[@class="post-meta"]/time/@datetime'
      match-rule: 'first'
    categories:
      select-method: 'xpath'
      select-expression: '//div[@class="breadcrumbs"]/a/text()'
      match-rule: 'all'

```
